#!/usr/bin/env python

# create the sourcy database (from the sqlalchemy definition in models.py)

from optparse import OptionParser
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

from tornado.options import define, options

from pprint import pprint
from sourcy.models import Base
from sourcy.util import parse_config_file


def main():
    parse_config_file("sourcy.conf")

#    parser = OptionParser()
#    (opts, args) = parser.parse_args()
#    if len(args) != 2:
#        parser.error("requires 2 args: <kind> <infile>")

    eng_url = "mysql+mysqldb://%(user)s:%(password)s@%(host)s/%(db)s?charset=utf8" % {
        'user': options.mysql_user,
        'password': options.mysql_password,
        'host': options.mysql_host,
        'db': options.mysql_database
    }
    engine = create_engine(eng_url, echo=True)
#    Session = sessionmaker(bind=engine)
#    session = Session()


    Base.metadata.create_all(engine)


if __name__ == "__main__":
    main()

