#!/usr/bin/env python

# create the sourcy database (from the sqlalchemy definition in models.py)

from optparse import OptionParser
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

from tornado.options import define, options

from pprint import pprint
from sourcy.models import Base, Tag, TagKind
from sourcy.util import parse_config_file


def main():
    parse_config_file("sourcy.conf")

#    parser = OptionParser()
#    (opts, args) = parser.parse_args()
#    if len(args) != 2:
#        parser.error("requires 2 args: <kind> <infile>")

    eng_url = "mysql+mysqldb://%(user)s:%(password)s@%(host)s/%(db)s?charset=utf8" % {
        'user': options.mysql_user,
        'password': options.mysql_password,
        'host': options.mysql_host,
        'db': options.mysql_database
    }
    engine = create_engine(eng_url, echo=True)


    Base.metadata.create_all(engine)

    Session = sessionmaker(bind=engine)
    session = Session()

    tag_defs = (
        {
        'name': 'warn_wikipedia',
        'description': 'This article contains unsourced, unverified information from Wikipedia.',
        'kind': TagKind.WARNING,
        'icon': 'warn_wikipedia',
        },
        {
        'name': 'warn_anon',
        'description': 'This article is based on an unverified, anonymous tipoff.',
        'kind': TagKind.WARNING,
        'icon': 'warn_anon',
        },
        {
        'name': 'warn_soft',
        'description': 'To ensure future interviews with subject, important questions were not asked.',
        'kind': TagKind.WARNING,
        'icon': 'warn_soft',
        },
        {
        'name': 'warn_churn',
        'description': 'This article is basically just a press release, copied and pasted.',
        'kind': TagKind.WARNING,
        'icon': 'warn_churn',
        },
        {
        'name': 'warn_pr',
        'description': 'Statistics, survey results and/or equations in this article were sponsored by a PR company.',
        'kind': TagKind.WARNING,
        'icon': 'warn_pr',
        },
        {
        'name': 'science',
        'description':  'Science',
        'kind': TagKind.GENERAL,
        'icon': 'science',
        },
        {
        'name': 'unsourced',
        'description': 'This article might be missing some sources',
        'kind': TagKind.ADMIN,
        'icon': 'unsourced',
        },
        {
        'name': 'help',
        'description': 'Help requested tracking down sources for this article',
        'kind': TagKind.ADMIN,
        'icon': 'help',
        }
    )

    for tag_def in tag_defs:
        t = Tag(**tag_def)
        session.add(t)
    session.commit()

if __name__ == "__main__":
    main()

