"""support anon user

Revision ID: 287f26a91c49
Revises: 34a74aec6664
Create Date: 2013-01-07 15:48:14.103197

"""

# revision identifiers, used by Alembic.
revision = '287f26a91c49'
down_revision = '34a74aec6664'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('useraccount', sa.Column('anonymous', sa.Boolean(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('useraccount', 'anonymous')
    ### end Alembic commands ###
