"""Initial alembic run

Revision ID: 2955ce09cc6e
Revises: None
Create Date: 2012-04-17 10:13:32.241183

"""

# revision identifiers, used by Alembic.
revision = '2955ce09cc6e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
