"""comments reference users

Revision ID: 2bae732a93ed
Revises: 4bbad70ca644
Create Date: 2012-05-18 12:20:23.033717

"""

# revision identifiers, used by Alembic.
revision = '2bae732a93ed'
down_revision = '4bbad70ca644'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment_user_map',
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.Column('useraccount_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], ),
    sa.ForeignKeyConstraint(['useraccount_id'], ['useraccount.id'], ),
    sa.PrimaryKeyConstraint()
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment_user_map')
    ### end Alembic commands ###
