"""cruft removal

Revision ID: 47f6606cd6c4
Revises: 1b03fe490363
Create Date: 2012-06-06 14:13:15.511380

"""

# revision identifiers, used by Alembic.
revision = '47f6606cd6c4'
down_revision = '1b03fe490363'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('useraccount', u'verified')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('useraccount', sa.Column(u'verified', mysql.TINYINT(display_width=1), nullable=False))
    ### end Alembic commands ###
