"""add file uploads

Revision ID: 4bbad70ca644
Revises: 57b7d7bbc6aa
Create Date: 2012-04-25 22:08:31.511106

"""

# revision identifiers, used by Alembic.
revision = '4bbad70ca644'
down_revision = '57b7d7bbc6aa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploaded_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=256), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('uploaded', sa.DateTime(), nullable=False),
    sa.Column('is_img', sa.Boolean(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.CheckConstraint('TODO'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'useraccount', sa.Column('photo_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'useraccount', 'photo_id')
    op.drop_table('uploaded_file')
    ### end Alembic commands ###
