"""add token table

Revision ID: 4c4e5c2be6a
Revises: 2bae732a93ed
Create Date: 2012-05-23 15:59:34.298502

"""

# revision identifiers, used by Alembic.
revision = '4c4e5c2be6a'
down_revision = '2bae732a93ed'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('expires', sa.DateTime(), nullable=False),
    sa.Column('payload', sa.String(length=2048), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token')
    ### end Alembic commands ###
