SET SESSION storage_engine = "InnoDB";
SET SESSION time_zone = "+0:00";
ALTER DATABASE CHARACTER SET "utf8";

DROP TABLE IF EXISTS article;
CREATE TABLE article (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    headline VARCHAR(512) NOT NULL,
    publication VARCHAR(512) NOT NULL,
    permalink VARCHAR(512) NOT NULL,
    pubdate DATETIME,
    created DATETIME NOT NULL
);


DROP TABLE IF EXISTS useraccount;
CREATE TABLE useraccount (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(128) NOT NULL UNIQUE,
    name VARCHAR(128) NOT NULL,
    anonymous BOOLEAN NOT NULL,
    created DATETIME NOT NULL
);


DROP TABLE IF EXISTS source;
CREATE TABLE source (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    article_id INT REFERENCES article(id),
    url VARCHAR(512) NOT NULL DEFAULT '',
    doi VARCHAR(128) NOT NULL DEFAULT '',
    title VARCHAR(512) NOT NULL DEFAULT '',
    creator INT REFERENCES user(id),
    created DATETIME NOT NULL
);


